// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2suHYfNONzPPkkfpKEl1LQkyK4J0s8Hw',
    appId: '1:376117705427:web:af9fe52a16cae4251eb226',
    messagingSenderId: '376117705427',
    projectId: 'e-donation-community-v2',
    authDomain: 'e-donation-community-v2.firebaseapp.com',
    storageBucket: 'e-donation-community-v2.firebasestorage.app',
    measurementId: 'G-29VLL68HNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Q_DzH4L5a2_UIaNFOWGIxQNXtpNV-cc',
    appId: '1:376117705427:android:78ca6105bfcf57c11eb226',
    messagingSenderId: '376117705427',
    projectId: 'e-donation-community-v2',
    storageBucket: 'e-donation-community-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFtOU8WosGMYMJ9c6ELz5yeb4xZMhk9fU',
    appId: '1:376117705427:ios:835b29ebb46e53d61eb226',
    messagingSenderId: '376117705427',
    projectId: 'e-donation-community-v2',
    storageBucket: 'e-donation-community-v2.firebasestorage.app',
    iosClientId: '376117705427-5i12d7jmoehq22p95g54lrfqg5k4unsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.edcV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFtOU8WosGMYMJ9c6ELz5yeb4xZMhk9fU',
    appId: '1:376117705427:ios:835b29ebb46e53d61eb226',
    messagingSenderId: '376117705427',
    projectId: 'e-donation-community-v2',
    storageBucket: 'e-donation-community-v2.firebasestorage.app',
    iosClientId: '376117705427-5i12d7jmoehq22p95g54lrfqg5k4unsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.edcV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2suHYfNONzPPkkfpKEl1LQkyK4J0s8Hw',
    appId: '1:376117705427:web:3f751c1b0c144ad71eb226',
    messagingSenderId: '376117705427',
    projectId: 'e-donation-community-v2',
    authDomain: 'e-donation-community-v2.firebaseapp.com',
    storageBucket: 'e-donation-community-v2.firebasestorage.app',
    measurementId: 'G-XM2VBV6SRT',
  );
}
